DROP SCHEMA IF EXISTS notes_system  CASCADE;
CREATE SCHEMA IF NOT EXISTS notes_system ;

CREATE TABLE notes_system.notes(
    ID TEXT NOT NULL PRIMARY KEY,
    TITLE TEXT NOT NULL ,
    DESCRIPTION TEXT NOT NULL,
    PRIORITY NUMERIC NOT NULL
);

SELECT * FROM notes_system.notes;